---
services:
  kafka:
    image: confluentinc/cp-kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.243.99:9092 # 192.168.243.99 -> replace with your desktop's ip
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    networks:
      - kafka-zookeeper-network
    depends_on:
      - zookeeper

  zookeeper:
    image: zookeeper
    ports:
      - 2181:2181
    networks:
      - kafka-zookeeper-network
networks:
  kafka-zookeeper-network: